/* keyedfi.c -- Keyword table for EDIF keywords */

/* Copyright (C) 1993 -- Data I/O Corporation -- All Rights Reserved.
 *
 * This program is protected under the copyright laws as a published work.
 * It may not be copied, reproduced, further distributed, adaptations
 * made from the same, or used to prepare derivative works, without the
 * prior written consent of the Data I/O Corporation
 *
 * History:
 *    5/05/93 - Included in Version 2.5
 */

#include "stdafx.h"
#include "key.h"

char *keyword[] =
 {
   "ANNOTATE",
   "ARC",
   "ARRAY",
   "BOOLEANVALUE",
   "BORDERWIDTH",
   "BOUNDINGBOX",
   "CELL",
   "CELLTYPE",
   "CIRCLE",
   "CONNECTLOCATION",
   "CURVE",
   "DCFANOUTLOAD",
   "DCMAXFANOUT",
   "DESIGNATOR",
   "DIRECTION",
   "DISPLAY",
   "DOT",
   "E",
   "EDIF",
   "EDIFLEVEL",
   "EDIFVERSION",
   "FALSE",
   "FIGURE",
   "FIGUREGROUP",
   "FIGUREGROUPOVERRIDE",
   "GRIDMAP",
   "INSTANCE",
   "INTEGER",
   "INTEGERDISPLAY",
   "INTERFACE",
   "JUSTIFY",
   "KEYWORDDISPLAY",
   "KEYWORDLEVEL",
   "KEYWORDMAP",
   "LIBRARY",
   "MEMBER",
   "NAME",
   "NUMBERDEFINITION",
   "NUMBERDISPLAY",
   "OPENSHAPE",
   "ORIENTATION",
   "ORIGIN",
   "PATH",
   "PATHWIDTH",
   "POINTLIST",
   "POLYGON",
   "PORT",
   "PORTIMPLEMENTATION",
   "PORTREF",
   "PROPERTY",
   "PROPERTYDISPLAY",
   "PT",
   "RECTANGLE",
   "RENAME",
   "SCALE",
   "SHAPE",
   "STRING",
   "STRINGDISPLAY",
   "SYMBOL",
   "TECHNOLOGY",
   "TEXTHEIGHT",
   "TRUE",
   "UNIT",
   "VIEW",
   "VIEWTYPE",
   "VISIBLE",
/* UNUSED KEYWORDS WHICH MAY OCCUR */
   "ACLOAD",
   "ARRAYRELATEDINFO",
   "BOOLEAN",
   "BORDERPATTERN",
   "COLOR",
   "COMMENT",
   "COMMENTGRAPHICS",
   "CONTENTS",
   "CORNERTYPE",
   "DESIGN",
   "ENDTYPE",
   "EXTERNAL",
   "FABRICATE",
   "FILLPATTERN",
   "INCLUDEFIGUREGROUP",
   "INSTANCE",
   "JOINED",
   "MINOMAX",
   "MUSTJOIN",
   "NUMBER",
   "OWNER",
   "PAGESIZE",
   "PARAMETER",
   "PARAMETERDISPLAY",
   "PERMUTABLE",
   "PHYSICALDESIGNRULE",
   "POINT",
   "PORTBUNDLE",
   "PORTDELAY",
   "PROTECTIONFRAME",
   "SIMULATE",
   "SIMULATIONINFO",
   "STATUS",
   "TIMING",
   "UNUSED",
   "USERDATA",
   "VIEWMAP",
   "WEAKJOINED",
   ""
 };


char *constant[] =
 {
   "ANGLE",
   "BEHAVIOR",
   "CALCULATED",
   "CAPACITANCE",
   "CENTERCENTER",
   "CENTERLEFT",
   "CENTERRIGHT",
   "CHARGE",
   "CONDUCTANCE",
   "CURRENT",
   "DISTANCE",
   "DOCUMENT",
   "ENERGY",
   "EXTEND",
   "FLUX",
   "FREQUENCY",
   "GENERIC",
   "GRAPHIC",
   "INDUCTANCE",
   "INOUT",
   "INPUT",
   "LOGICMODEL",
   "LOWERCENTER",
   "LOWERLEFT",
   "LOWERRIGHT",
   "MASKLAYOUT",
   "MASS",
   "MEASURED",
   "MX",
   "MXR90",
   "MY",
   "MYR90",
   "NETLIST",
   "OUTPUT",
   "PCBLAYOUT",
   "POWER",
   "R0",
   "R180",
   "R270",
   "R90",
   "REQUIRED",
   "RESISTANCE",
   "RIPPER",
   "ROUND",
   "SCHEMATIC",
   "STRANGER",
   "SYMBOLIC",
   "TEMPERATURE",
   "TIE",
   "TIME",
   "TRUNCATE",
   "UPPERCENTER",
   "UPPERLEFT",
   "UPPERRIGHT",
   "VOLTAGE",
   ""
 };
